
# Project information
site_name: 'Python Tutorials'
site_description: 'A tutorial to python'
site_author: 'San Diego Code'
site_url: 'https://sandiegocode/python'

pages:
- Home: index.md
- Lesson 1:  lesson1.md
- Lesson 2: lesson2.md
- Lesson 3: lesson3.md
- Lesson 4: lesson4.md
- Lesson 5: lesson5.md
- Lesson 6: lesson6.md
- GUI: lesson7.md
- String Formatting: lesson8.md
- Challenges: challenges.md

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/sandiegocode/python'

# Copyright
copyright: © San Diego Code

# Documentation and theme
theme: 'material'

# Options
extra:
  palette:
    primary: 'purple'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'sandiegocode'
  disqus: 'sandiegocode'

# Extensions
markdown_extensions:
  - admonition

#Compiler Code
extra_css: [compiler.css, button.css]
extra_javascript: [imports.js, compiler.js, main.js]
